import '../globals.scss'
import { Inter } from 'next/font/google'
import 'react-toastify/dist/ReactToastify.css'
import Header from '../../components/header/Header'
import styles from './layout.module.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <>
            <Header />
            <main className={styles.main}>{children}</main>
        </>
    )
}
